"""add_verification_codes

Revision ID: 099794a7b57c
Revises: d654ca6da8dc
Create Date: 2026-05-26 13:32:11.833341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '099794a7b57c'
down_revision: Union[str, None] = 'd654ca6da8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_phone'), 'verification_codes', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_phone'), table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
