"""init

Revision ID: 681d18f20f34
Revises: 8f9b62fb8442
Create Date: 2026-05-26 14:58:01.239776
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '681d18f20f34'
down_revision: Union[str, None] = '8f9b62fb8442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
