"""init

Revision ID: 8f9b62fb8442
Revises: 94f8e14da90e
Create Date: 2026-05-26 14:56:32.589282
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f9b62fb8442'
down_revision: Union[str, None] = '94f8e14da90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
