"""init

Revision ID: 94f8e14da90e
Revises: 099794a7b57c
Create Date: 2026-05-26 13:36:26.009995
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94f8e14da90e'
down_revision: Union[str, None] = '099794a7b57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
